version: '3'
services:
  app:
    container_name: taxi24_app
    build: .
    ports:
      - "${APP_PORT}:3000"
    environment:
      APP_PORT: ${APP_PORT}
      APP_ENV: ${APP_ENV}
      DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      - db

  db:
    container_name: taxi24_db
    image: postgres:16.4-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
