import { ApiProperty } from '@nestjs/swagger';

export class GetDriversResponseDto {
  @ApiProperty({
    description: 'Unique identifier for the driver, generated by the system.',
    example: '123e4567-e89b-12d3-a456-426614174000',
  })
  id: string;

  @ApiProperty({
    description: 'Full name of the driver.',
    example: 'John Doe',
  })
  name: string;

  @ApiProperty({
    description: 'License number of the driver.',
    example: 'LIC1234567',
  })
  licenseNumber: string;

  @ApiProperty({
    description: 'Email address of the driver, must be unique.',
    example: 'johndoe@example.com',
  })
  email: string;

  @ApiProperty({
    description: 'Phone number of the driver, must be unique.',
    example: '+18095551234',
  })
  phoneNumber: string;

  @ApiProperty({
    description: 'Availability status of the driver.',
    example: true,
    default: true,
  })
  isAvailable: boolean;

  @ApiProperty({
    description: "Current latitude of the driver's location.",
    type: 'number',
    format: 'double',
    example: 37.7749,
    required: false,
  })
  locationLatitude: number;

  @ApiProperty({
    description: "Current longitude of the driver's location.",
    type: 'number',
    format: 'double',
    example: -122.4194,
    required: false,
  })
  locationLongitude: number;
}
